### ISSUE TITLE
Directory does not exist: /home/user/eclipse/features

### ISSUE THREAD

**Issue by footballsingh0723** [senny/emacs-eclim#284]
jar:file:/home/user/Downloads/eclim_2.6.0.jar!/installer.xml:145: The following error occurred while executing this line:
jar:file:/user/gagan/Downloads/eclim_2.6.0.jar!/installer.xml:342: Directory does not exist: /home/user/eclipse/features
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:460)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.formic.wizard.step.shared.InstallAction.execute(InstallAction.java:124)
	at org.formic.wizard.step.gui.InstallStep$1.run(InstallStep.java:162)
	at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
	at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
	at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
	at java.lang.Thread.run(Thread.java:745)

Caused by: jar:file:/home/user/Downloads/eclim_2.6.0.jar!/installer.xml:342: Directory does not exist: /home/user/eclipse/features
	at org.apache.tools.ant.taskdefs.Delete.handle(Delete.java:704)
	at org.apache.tools.ant.taskdefs.Delete.execute(Delete.java:613)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
	... 19 more

**Comment by nloyola** [comment]
Note that development for this package has moved to here: https://github.com/emacs-eclim/emacs-eclim

It appears that you have not installed Eclipse before installing [Eclim 2.6.0](http://eclim.org/install.html). If you have installed Eclipse, what directory did you install it to?

**Comment by footballsingh0723** [comment]
I installed it in, ~/home/user/eclipse. When the eclim gui installer asks for the eclipse home, I enter in this path.

**Comment by nloyola** [comment]
You should then have the following directories in `~/home/user/eclipse`:

```
~/home/user/eclipse/configuration
~/home/user/eclipse/dropins
~/home/user/eclipse/features
~/home/user/eclipse/p2
~/home/user/eclipse/plugins
~/home/user/eclipse/readme
```

Are they there?

**Comment by nloyola** [comment]
Actually `~/home/user/eclipse` is not the same as `/home/user/eclipse`. Eclim is looking for Eclipse in `home/user/eclipse`. 

`~/home/user/eclipse` would be a subdirectory under your HOME directory.

**Comment by footballsingh0723** [comment]
Sorry, the directory that I eclipse is installed in is, /home/gagan/eclipse not ~/home/user/eclipse.
I have all the directories that you mentioned.

**Comment by footballsingh0723** [comment]
Done....!
Reinstalled eclipse, restarted my machine.
Works fine.
